CREATE TABLE IF NOT EXISTS panel_client_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  node_id VARCHAR(96) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  remote_addr VARCHAR(128) NOT NULL DEFAULT '',
  user_id VARCHAR(128) NOT NULL DEFAULT '',
  device_id VARCHAR(128) NOT NULL DEFAULT '',
  client_id VARCHAR(128) NOT NULL DEFAULT '',
  client_version VARCHAR(64) NOT NULL DEFAULT '',
  client_platform VARCHAR(64) NOT NULL DEFAULT '',
  protocol_version INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('online','closed') NOT NULL DEFAULT 'online',
  close_reason VARCHAR(64) NOT NULL DEFAULT '',
  close_source VARCHAR(32) NOT NULL DEFAULT '',
  game_ids JSON NULL,
  policy_ids JSON NULL,
  config_revision VARCHAR(64) NOT NULL DEFAULT '',
  connected_at DATETIME NOT NULL,
  authenticated_at DATETIME NULL,
  last_seen_at DATETIME NOT NULL,
  last_ping_at DATETIME NULL,
  ended_at DATETIME NULL,
  duration_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
  max_connections INT UNSIGNED NOT NULL DEFAULT 0,
  rate_limit_mbps INT UNSIGNED NOT NULL DEFAULT 0,
  allow_tcp TINYINT(1) NOT NULL DEFAULT 1,
  allow_udp TINYINT(1) NOT NULL DEFAULT 1,
  udp_flows INT UNSIGNED NOT NULL DEFAULT 0,
  tcp_flows INT UNSIGNED NOT NULL DEFAULT 0,
  udp_client_to_target_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  udp_target_to_client_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tcp_client_to_target_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  tcp_target_to_client_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_node_session (node_id, session_id),
  KEY idx_user_time (user_id, connected_at),
  KEY idx_device_time (device_id, connected_at),
  KEY idx_node_status_time (node_id, status, last_seen_at),
  KEY idx_close_reason (close_reason, ended_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS panel_client_session_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  node_id VARCHAR(96) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  user_id VARCHAR(128) NOT NULL DEFAULT '',
  device_id VARCHAR(128) NOT NULL DEFAULT '',
  close_reason VARCHAR(64) NOT NULL DEFAULT '',
  close_source VARCHAR(32) NOT NULL DEFAULT '',
  occurred_at DATETIME NOT NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_node_session_event (node_id, session_id, occurred_at),
  KEY idx_user_event_time (user_id, occurred_at),
  KEY idx_event_type_time (event_type, occurred_at),
  KEY idx_close_reason_time (close_reason, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
