-- 控制面板数据库缺失中文注释补丁。
-- 用途：在 Navicat 或 MySQL 客户端中直接执行，给现有表补充表注释和字段注释。
-- 适用库：gaccel-panel 控制面板使用的 MySQL 数据库。

SET NAMES utf8mb4;

ALTER TABLE panel_client_sessions
  COMMENT = '客户端连接会话表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN node_id VARCHAR(96) NOT NULL COMMENT '节点唯一 ID',
  MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT '节点内会话 ID',
  MODIFY COLUMN remote_addr VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户端来源地址',
  MODIFY COLUMN user_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '业务用户 ID',
  MODIFY COLUMN device_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户端设备 ID',
  MODIFY COLUMN client_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户端实例 ID',
  MODIFY COLUMN client_version VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端版本',
  MODIFY COLUMN client_platform VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端平台，例如 windows/amd64',
  MODIFY COLUMN protocol_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '节点协议版本',
  MODIFY COLUMN status ENUM('online','closed') NOT NULL DEFAULT 'online' COMMENT '会话状态：online 在线，closed 已结束',
  MODIFY COLUMN close_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '断开原因，例如 client_shutdown、heartbeat_timeout',
  MODIFY COLUMN close_source VARCHAR(32) NOT NULL DEFAULT '' COMMENT '断开来源：client、node、timeout 等',
  MODIFY COLUMN game_ids JSON NULL COMMENT 'token 授权的游戏 ID 列表',
  MODIFY COLUMN policy_ids JSON NULL COMMENT 'token 授权的策略 ID 列表',
  MODIFY COLUMN config_revision VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端配置版本',
  MODIFY COLUMN connected_at DATETIME NOT NULL COMMENT 'QUIC 连接建立时间',
  MODIFY COLUMN authenticated_at DATETIME NULL COMMENT '认证成功时间',
  MODIFY COLUMN last_seen_at DATETIME NOT NULL COMMENT '最近活跃或上报时间',
  MODIFY COLUMN last_ping_at DATETIME NULL COMMENT '最近一次 PING 时间',
  MODIFY COLUMN ended_at DATETIME NULL COMMENT '会话结束时间',
  MODIFY COLUMN duration_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '会话持续秒数',
  MODIFY COLUMN max_connections INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'token 允许的最大连接数',
  MODIFY COLUMN rate_limit_mbps INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'token 限速 Mbps',
  MODIFY COLUMN allow_tcp TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'token 是否允许 TCP',
  MODIFY COLUMN allow_udp TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'token 是否允许 UDP',
  MODIFY COLUMN udp_flows INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前或最近 UDP flow 数',
  MODIFY COLUMN tcp_flows INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前或最近 TCP flow 数',
  MODIFY COLUMN udp_client_to_target_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UDP 客户端到目标字节数',
  MODIFY COLUMN udp_target_to_client_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UDP 目标到客户端字节数',
  MODIFY COLUMN tcp_client_to_target_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'TCP 客户端到目标字节数',
  MODIFY COLUMN tcp_target_to_client_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'TCP 目标到客户端字节数',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE panel_client_session_events
  COMMENT = '客户端会话事件表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN node_id VARCHAR(96) NOT NULL COMMENT '节点唯一 ID',
  MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT '节点内会话 ID',
  MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '事件类型，例如 session_started、authenticated、session_ended',
  MODIFY COLUMN user_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '业务用户 ID',
  MODIFY COLUMN device_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户端设备 ID',
  MODIFY COLUMN close_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT '断开原因',
  MODIFY COLUMN close_source VARCHAR(32) NOT NULL DEFAULT '' COMMENT '断开来源',
  MODIFY COLUMN occurred_at DATETIME NOT NULL COMMENT '事件发生时间',
  MODIFY COLUMN payload_json JSON NULL COMMENT '事件扩展内容 JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间';

ALTER TABLE panel_node_task_logs
  COMMENT = '节点运维任务日志表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN task_id VARCHAR(96) NOT NULL COMMENT '任务唯一 ID',
  MODIFY COLUMN node_id VARCHAR(96) NOT NULL COMMENT '节点唯一 ID',
  MODIFY COLUMN step VARCHAR(96) NOT NULL COMMENT '任务执行步骤',
  MODIFY COLUMN stream ENUM('info','stdout','stderr','error') NOT NULL DEFAULT 'info' COMMENT '日志流类型',
  MODIFY COLUMN message TEXT NOT NULL COMMENT '日志内容',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE panel_token_defaults
  COMMENT = '客户端 token 默认档位表',
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN plan_id VARCHAR(64) NOT NULL COMMENT '档位 ID，例如 trial、standard、advanced、premium',
  MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '档位展示名称',
  MODIFY COLUMN max_connections INT UNSIGNED NOT NULL COMMENT '默认最大连接数',
  MODIFY COLUMN rate_limit_mbps INT UNSIGNED NOT NULL COMMENT '默认限速 Mbps',
  MODIFY COLUMN allow_tcp TINYINT(1) NOT NULL DEFAULT 1 COMMENT '默认是否允许 TCP',
  MODIFY COLUMN allow_udp TINYINT(1) NOT NULL DEFAULT 1 COMMENT '默认是否允许 UDP',
  MODIFY COLUMN description VARCHAR(255) NOT NULL DEFAULT '' COMMENT '档位说明',
  MODIFY COLUMN sort_order INT NOT NULL DEFAULT 100 COMMENT '排序值，越小越靠前',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

